//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string ATTACKEDRIFLE_BODY = "attackedrifle_body";
        
        public const string ATTACKEDSNIPER_BODY = "attackedsniper_body";
        
        public const string IN_THE_SMOKESHELL = "in_the_smokeshell";
        
        public const string HEARTBEAT = "heartbeat";
        
        public const string ATTACKEDPISTOL_BODY = "attackedpistol_body";
        
        public const string HEARTBEAT_FAST = "heartbeat_fast";
        
        public const string ATTACKEDSHOTGUN_BODY = "attackedshotgun_body";
    }
}
